version: "3.9"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16.3
    ports:
      - "55432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-skins-data:/var/lib/postgresql/data

volumes:
  pg-skins-data: